---
title: "The Sum of a Magic Square of Squares Must Be an Odd-Power"
author: "Hyun Joon"
date: "2026-05-10"
categories: ["magic squares"]
format: html
---

# Motivation
After looking at the results from the code. One can guess that there isn't a 3x3 magic square of squares whose sum is a perfect square.
At first this seemed very hard to prove, well that is until a fun fact about all 3 by 3 magic squares share
That its sum is equal to 3 times the number in the center.
With this simple fact a simple proof by contradiction would seem to work best, for we leverage the irrationality of the square root of 3.  
But first, we'll have to prove that the sum of any 3x3 magic square really is 3 times its center number

## The Proof for the Fun Fact

For any 3 by 3 magic square the sum is equal to 3 times its center value. This surprising is pretty simple to prove.
First, an arbitrary 3x3 magic square:
$$
\begin{array}{c|c|c}
A & B & C \\ \hline
D & E & F \\ \hline
G & H & I
\end{array}
$$  
Now because this is a magic square its elements, in each row, column, and diagonal, when summed adds to a single value. Let's call this value S.  
\begin{align*}
&\text{So, we have}\\
&A + B + C = S,\ D + E + F = S,\ G + H + I = S\ \text{for each row}\\
&A + D + G = S,\ B + E + H = S,\ C + F + I = S\ \text{for each column}\\
&A + E + I = S,\ C + E + G = S\ \text{for each diagonal}\\
\end{align*}

Now, take the four equations
\begin{align*}
D + E + F = S \\ A + E + I = S \\ B + E + H = S \\ C + E + G = S
\end{align*}  
Observe that
\begin{align*}
4S &= (D + E + F) + (A + E + I) + (B + E + H) + (C + E + G)\\
&= D + E + F + A + E + I + B + E + H + C + E + G
\end{align*}  
Suggestively rewrite the right most side and left most side, and collect like terms
\begin{align*}
4S &= E + E + E + A + B + C + D + E + F + G + H + I\\
&= 3E + (A + B + C) + (D + E + F) + (G + H + I)
\end{align*}  
Remember the three equations $A + B + C = S,\ D + E + F = S,\ G + H + I = S$  
Simplify the previous expression with it, and collect like terms
\begin{align*}
&4S = 3E + (A + B + C) + (D + E + F) + (G + H + I) = 3E + 3S\\
&\Longrightarrow\ 4S = 3E + 3S\\
&\therefore S = 3E
\end{align*}

Hence, it has been demonstrated that the sum for an arbitrary 3 by 3 magic square is 3 times its center value.

## The Proof for Squares


# Observations & Generalizations
The proof for squares seems to be easily generalizable to any even power and with a clever insight to all perfect powers. The next section does exactly this.

## For All Even Powers

"PLACE_HOLDER"

## For Odd Powers

A similar proof was thought of for all odd powers, but after further inspection the proof didn't work so unfortunately there isn't one for all odd powers.  
In fact, contrary to expectations any odd power can't be disproven to be the sum only leverging the irrationality of 3.
There might be other ways of disproving specific odd powers of all odd powers all together, but it hasn't been found.

# Conclusion
With these simple proof the sum for a 3x3 magic square is an odd power, like $1, 2, 3, 5, 6, 7, 8, 10, 11, 12, \text{etc.}$
